# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title            : "Ai Yang's Academic Homepage"
description      : "Personal Website of Ai Yang, Data Science Undergraduate at Hebei University of Technology."
repository       : "auutuumn0017/auutuumn0017.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Ai Yang"
  avatar           : "images/android-chrome-512x512.png" # 稍后你可以把你的头像重命名为这个名字并替换到images文件夹里
  bio              : "Undergraduate in Data Science and Big Data Technology, Hebei University of Technology"
  location         : "China"
  employer         :
  pubmed           :
  googlescholar    : 
  email            : "235127@stu.hebut.edu.cn"
  researchgate     :  
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "auutuumn0017"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : 
  dblp             : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
